mysite/events/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from . import views
from home.models import Titles


urlpatterns = [
    url(r'^(?P<titles_Title>[\w\-]+)$', views.create_post, name = 'create_post'),
    url(r'^(?P<titles_Title>[\w\-]+)/post_details', views.post_details, name='post_details'),
    url(r'^(?P<titles_Title>[\w\-]+)/book_details', views.book_details, name='book_details'),
    url(r'^events_template', views.events_form)
    ]

mysite/home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from . import views
from home.models import Titles
from .views import ChartData
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^events/', include('events.urls', namespace = 'events')),
    url(r'^add_title/$', views.add_title, name = 'add_title'),
    url(r'^profile/$', views.ProfileView, name = 'profile'),
    url(r'^api/chart/data/$', ChartData.as_view()),
    
    
    ]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace = 'home')),
    url(r'^events/', include('events.urls', namespace = 'events')),
    url(r'^accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/home/models.py
from django.db import models
from django.contrib.auth.models import User, Permission



class Titles(models.Model):
    user = models.ForeignKey(User, default =1)
    profit = models.BigIntegerField(default = 0)
    Title = models.CharField(max_length=250)
    Title_logo = models.FileField(upload_to='photos')
    def __str__(self):
        return self.Title

mysite/home/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Titles



class TitlesForm(forms.ModelForm):

    class Meta:
        model = Titles
        fields = ['Title', 'Title_logo']

mysite/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Titles
from events.models import events
from django.db.models import Q
from django.views.generic import View
from .forms import TitlesForm
from events.forms import eventsForm
from events.models import Posts
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth import get_user_model
from events.forms import eventsForm

User = get_user_model()
def index(request):
    titles = Titles.objects.filter(user=request.user)
    event = events.objects.all()
    form = eventsForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        event = form.save(commit=True)
        return render(request, 'home/home.html', {'titles':titles, 'form': form})
    if not request.user.is_authenticated():
        return render(request, 'account/login.html')
    if request.method == 'POST':
        form = eventsForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.save()
            title.Title_logo = request.FILES['Title_logo']
    
    return render(request, 'home/home.html', {'titles':titles, 'form': form,'events':event})



def add_title(request):
    titles = Titles.objects.filter(user=request.user)
    form = TitlesForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        title = form.save(commit=False)
        title.user = request.user
        title.save()
        return render(request, 'home/home.html', {'titles':titles})
    return render(request, 'home/add_title.html', {'form':form})


def ProfileView(request):
    user = request.user
    titles = Titles.objects.all()
    posts = Posts.objects.all()
    return render(request, 'home/profile.html', {'user':user,'titles':titles, 'posts':posts})

    
def labelsNum(number):
    x_axis = []
    for i in range(number):
        x_axis.append(i)
    return x_axis



class ChartData(APIView):

    authentication_classes = []
    permission_classes = []
    

    def get(self, request, format=None):
        qs_count = User.objects.all().count()
        posts = Posts.objects.all()
        profit = 0
        default_items = []
        profits = []
        for post in posts:
            default_items.append(post.receive_ammount - post.bet_ammount)
        for i in range(len(default_items)):
            if i == 0:
                profits.append(default_items[i])
            else:
                profits.append(default_items[i]+profits[i-1])
            
        labels = labelsNum(len(default_items))
            
        data = {
            "default": profits,
  
            "labels": labels,

            }
        all_titles = Titles.objects.all()
        for title in all_titles:
            single_items = []
            single_profits = []
            game_post = Posts.objects.filter(titles = title)
            for post in game_post:
                single_items.append(post.receive_ammount - post.bet_ammount)
            for i in range(len(single_items)):
                if i == 0:
                    profits.append(single_items[i])
                else:
                    profits.append(default_items[i]+profits[i-1])
            data[title.Title] = single_profits
        return JsonResponse(data)

mysite/home/templates/home/add_title.html
<!doctype html>
{% extends "home/header.html" %}

{% block content %}
<div class="container-fluid">

    <div class="row">
    
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Title</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Viberr?</h3>
                    <p>Viberr is an app that allows you to upload and store all of your music on the cloud.</p>
                    <h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

mysite/home/templates/home/base.html
<!DOCTYPE html>

<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Django + Charts.js</title>

    {% include 'home/base/css.html' %}
    {% include 'home/base/bootstrap_defaults.html' %}
  </head>
  
  <body>

    <div class='container'>

    {% block content %}


    {% endblock content %}
    </div>
    {% include 'home/base/js.html' %}
    <script>
    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })
    </script>

  </body>
</html>

mysite/home/templates/home/charts.html
{% extends 'base.html' %}

<script>
{% block jquery %}
var endpoint = '/api/chart/data/'
var defaultData = []
var labels = []
$.ajax({
    method:"GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
        // console.log(data.customers *234)

    },
    error: function(error_data){
        console.log("error")
        console.log(data)
    }
})
function setChart(){
    var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels:labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
}

{% endblock %}
</script>


{% block content %}

<div class='row'>
    <div class='col-sm-12'>
        <h1>Hello World </h1>
        <canvas id="myChart" width="400" height="400">yes</canvas>

    </div>
</div>

{% endblock content %}

mysite/home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/home/templates/home/header.html
<!DOCTYPE html>
<html lang="en">


<head>

	<title>{% if request.user.is_authenticated %}Logged In{% else %}Not Logged In{% endif %}</title>

	<meta charset="utf-8" />
	{% load staticfiles %}
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body>
	<nav class="navbar navbar-default navbar-static-top" role="navigation" style = 'margin-bottom:0;'>
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'home:index' %}">Betting24</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="{% url 'home:add_title' %}">Add Title <span class="sr-only">(current)</span></a></li>
	        <li><a href="#">Link</a></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	      	<li><a href = "/profile/">Profile</a></li>
	      	{% if request.user.is_authenticated %}
	        	<li><a href="/accounts/logout/">Logout</a></li>
	        	<li style = "display: inline-block;text-align:center;float: none;padding:0;border-radius:0px;border: none;">
	        		<img src="{{ request.user.profile.profile_image_url }}"/>
	        	</li>
	        	{% if request.user.first_name or request.user.last_name %}
	       			
	        		{{ request.user.first_name }} {{ request.user.last_name }}
	        	{% else %}
	        		{{ request.user.username }}
	        	{% endif %}
	    		{% if request.user.profile.account_verified %} (verified) {% else %} (unverified) {% endif %}
	    	{% else %}
	    		<li><a href="/accounts/login/" class="pull-right">Login</a></li>

			{% endif %}

	   
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.css"></script>
    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block content %}
		
	{% endblock %}

</body>


{% block extra_head %}
	<style type='text/css'>
		body{
			background-color:white;
			
		}
		.images{
			display: inline-block;
			width: 300px; 
			height: 120px; 
			border-radius: 0px; 
			border: 0;
			
		}
		.navbar-default{
			background-color:#2C3E50;
			border-color:black;
		}
		.navbar-default .navbar-brand{
			color:white;
		}
		.navbar-default .navbar-brand:hover,
		.navbar-default .navbar-brand:focus{
			color: #18BC9C;
			background-color: transparent;
		}
		.navbar-default .navbar-nav > li > a {
			color:white;
		}
		.navbar-default .navbar-nav > .active > a,
		.navbar-default .navbar-nav > .active > a:hover,
		.navbar-default .navbar-nav > .active > a:focus {
			color: #FFFFFF;
			background-color:#1A242F;
		}

	</style>
{% endblock %}
</html>

mysite/home/templates/home/home.html
<!doctype html>


{% extends "home/header.html" %}
{% block Titles_active %}active{% endblock %}

{% block content %}

<head>
	{% load staticfiles %}
	<title> My Webpage</title>

	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
	<body>
		<div class="jumbotron">
		<h1>Your Personal Book-Keeping</h1>
		<div class="container-fluid">
		  <div class="row-fluid">
		    <div class="col-xs-4">

		    </div>
		   </div>
		  </div>
		 </div>


	
	<div class="container" style = " width:1000px; margin: 75px;">
		<h2> Titles </h2>
	    <div class="row" style = "background-color:white;">
	        

	        {% if titles %}
	        	
	            {% for title in titles%}
	            	<div class="col-sm-4 col-lg-2" >
                		<div class="thumbnail" >
                			
               				<a href="{% url 'events:create_post' title.Title %}" class="thumbnail" >

                        		<img class="img-rounded" src="{{ title.Title_logo.url }}"  style="width: 350px; height: 125px; border-radius: 0px; ">
                        		<div class = "caption"> {{title.Title}} </div>
                    		</a>
                   		
                    	</div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
            {% endif %}
            </div>

    </div>


	<div class="well">
		<div class = 'container'>
			<h3> Upcomming Events <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
			  Add Event
			</button></h3>
			


			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Add Event</h4>
			      </div>
			      <div class="modal-body">
	                  <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
		                {% csrf_token %}
		                <input type="hidden" name="album" value="{{ album }}">
					        {% for field in form %}
							    <div class="form-group">
							        <div class="col-sm-offset-2 col-sm-10">
							            <span class="text-danger small">{{ field.errors }}</span>
							        </div>
							        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
							        <div class="col-sm-10">{{ field }}</div>
							    </div>
							{% endfor %}
		                <div class="form-group">
		                    <div class="col-sm-offset-2 col-sm-10">
		                        <button type="submit" class="btn btn-success">Save Changes</button>
		                    </div>
		                </div>
		            </form>

			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div>

	        
	        <table class="table table-striped">
	            <thead>

	            <tr>
	                <th> Title </th>
	                <th> Event </th>
	                <th> Date </th>
	                <th>players</th>


	            </tr>
	            </thead>
	            <tbody>
	                {% for event in events %}
	                    <tr>
	                        <td> {{event.titles}}
	                        <td> {{event.event}}
	                        <td> {{ event.date }} </td>
	                        <td > {{event.players}}</td>
	       
	                    </tr>

	                {% endfor %}
	            </tbody>
	        </table>
		</div>
	</div>
	
	

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
</body>

<style type='text/css'>

	.images{
		display: inline-block;

		border-radius: 0px; 
		border: 0;
		
	}


	.thumbnail {
	text-align:center;
	border: none;
	border-radius:0px;
	padding:0px;
	background-image: url("media/photos/content.jpg");



	}

	.thumbnail > li {
	display: inline-block;
	*display:inline; 
	float: none; 
	background-image: url("media/photos/images.jpg");
	}
	.jumbotron {

    margin-bottom: 0px;
    background-image: url("media/photos/images.jpg");
    background-repeat: no-repeat;
    background-size: 100% 100%;

    background-repeat: no-repeat;
    color: white;
    margin-bottom: 20px;

    text-shadow: black 0.3em 0.3em 0.3em;

}
    table {
      border-collapse: separate;
      border-spacing: 0 5px;
    }

    thead th {
      background-color: black;
      color: white;
    }

    tbody td {
      background-color: #EEEEEE;
    }

    tr td:first-child,
    tr th:first-child {
      border-top-left-radius: 6px;
      border-bottom-left-radius: 6px;
    }

    tr td:last-child,
    tr th:last-child {
      border-top-right-radius: 6px;
      border-bottom-right-radius: 6px;
    }
</style>
{% endblock %}	

mysite/home/templates/home/profile.html
{% include 'home/header.html' %}


<script>
{% block jquery %}
var endpoint = '/api/chart/data/'
var defaultData = []
var labels = []

$.ajax({
	method:"GET",
	url: endpoint,
	success: function(data){
		labels = data.labels
		defaultData = data.default
		setChart()
		// console.log(data.customers *234)

	},
	error: function(error_data){
		console.log("error")
		console.log(data)
	}
})

function setChart(){
	var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels:labels,
        datasets: [{
            label: 'Profit',
            data: defaultData,


            borderColor: [
                'green'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
}



{% endblock %}
</script>


{% block content %}

<div class='row' >

    <div class='container col-md-8' style = "  margin: 0 auto; background-color:#f5f5dc;">

        <div class = 'col-md-10' style = "">
            <canvas id="myChart" width="300" height="243"></canvas>

        </div>
        <div class = 'container col-md-2' >

        	<h3 style = ' font-weight:bold; font-style:italic;'> Titles </h3>
        	<a class = "myButton"> All </a>
        	{% for title in titles %}
        		<a  class="myButton">{{title}}</a>
        	{% endfor %}
        </div>

    </div>

    <div class="panel panel-default col-md-4" style = "background-color:#f5f5dc;">
        <div class="panel-body">

            <h3>Latest bets</h3>


            <table class="table table-striped ">
                <thead>

                <tr>
                    <th> team 1 </th>
                    <th> team 2 </th>
                    <th> Stake  </th>
                    <th>Results</th>
                    <th>Title </th>


                </tr>
                </thead>
                <tbody>
                    {% for bets in posts|slice:":10" %}
                        <tr>
                            <td> {{bets.team_1}}
                            <td> {{bets.team_2}}
                            <td> {{ bets.bet_ammount }} : {{bets.receive_ammount}}</td>
                            <td > {{bets.result}}</td>
                            <td> {{bets.titles}} </td>
           
                        </tr>

                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>

<script src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js"></script>

<style type='text/css'>
.myButton {
	-moz-box-shadow: 0px 0px 0px 0px #fff6af;
	-webkit-box-shadow: 0px 0px 0px 0px #fff6af;
	box-shadow: 0px 0px 0px 0px #fff6af;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ffec64), color-stop(1, #ffab23));
	background:-moz-linear-gradient(top, #ffec64 5%, #ffab23 100%);
	background:-webkit-linear-gradient(top, #ffec64 5%, #ffab23 100%);
	background:-o-linear-gradient(top, #ffec64 5%, #ffab23 100%);
	background:-ms-linear-gradient(top, #ffec64 5%, #ffab23 100%);
	background:linear-gradient(to bottom, #ffec64 5%, #ffab23 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffec64', endColorstr='#ffab23',GradientType=0);
	background-color:#ffec64;
	-moz-border-radius:10px;
	-webkit-border-radius:10px;
	border-radius:10px;
	border:3px solid #ffaa22;
	margin:1px;
	display:inline-block;
	cursor:pointer;
	color:#333333;
	font-family:Arial;
	font-size:15px;
	font-weight:bold;
	padding:3px 19px;
	text-decoration:none;
	text-shadow:0px 1px 0px #ffee66;
	text-align:center;
	width: 100px;
}
.myButton:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ffab23), color-stop(1, #ffec64));
	background:-moz-linear-gradient(top, #ffab23 5%, #ffec64 100%);
	background:-webkit-linear-gradient(top, #ffab23 5%, #ffec64 100%);
	background:-o-linear-gradient(top, #ffab23 5%, #ffec64 100%);
	background:-ms-linear-gradient(top, #ffab23 5%, #ffec64 100%);
	background:linear-gradient(to bottom, #ffab23 5%, #ffec64 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffab23', endColorstr='#ffec64',GradientType=0);
	background-color:#ffab23;
}
.myButton:active {
	position:relative;
	top:1px;
}
    table {
      border-collapse: separate;
      border-spacing: 0 5px;
    }

    thead th {
      background-color: #006DCC;
      color: white;
    }

    tbody td {
      background-color: #EEEEEE;
    }

    tr td:first-child,
    tr th:first-child {
      border-top-left-radius: 6px;
      border-bottom-left-radius: 6px;
    }

    tr td:last-child,
    tr th:last-child {
      border-top-right-radius: 6px;
      border-bottom-right-radius: 6px;
    }




</style>
{% endblock content %}