mysite/events/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from . import views
from home.models import Titles


urlpatterns = [
    url(r'^(?P<titles_Title>[\w\-]+)$', views.create_post, name = 'create_post'),
    url(r'^(?P<titles_Title>[\w\-]+)/post_details', views.post_details, name='post_details'),
    url(r'^(?P<titles_Title>[\w\-]+)/book_details', views.book_details, name='book_details'),
    url(r'^events_template', views.events_form)
    ]

mysite/home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from . import views
from home.models import Titles
from .views import ChartData
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^events/', include('events.urls', namespace = 'events')),
    url(r'^add_title/$', views.add_title, name = 'add_title'),
    url(r'^profile/$', views.ProfileView, name = 'profile'),
    url(r'^api/chart/data/$', ChartData.as_view()),
    
    
    ]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace = 'home')),
    url(r'^events/', include('events.urls', namespace = 'events')),
    url(r'^accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/events/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Titles
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount
from django.conf import settings
from datetime import datetime
from decimal import Decimal
from datetime import date
    
class Posts(models.Model):
    titles = models.ForeignKey(Titles,on_delete = models.CASCADE)
    team_1 = models.CharField(max_length=100)
    team_2 = models.CharField(max_length=100)
    bet_ammount = models.BigIntegerField()
    receive_ammount = models.BigIntegerField()
    result = models.BooleanField(default = False)
    profit = models.BigIntegerField(default = 0)
    def __str__(self):
        return self.team_1 + " vs " + self.team_2

class odds(models.Model):
    titles = models.ForeignKey(Titles,on_delete = models.CASCADE)
    team_1 = models.CharField(max_length=100)
    team_2 = models.CharField(max_length=100)
    event = models.CharField(max_length=100)
    odds = models.DecimalField(max_digits = 20, decimal_places = 4)
    result = models.CharField(max_length=100)
    def __str__(self):
        return self.team_1 + " vs " + self.team_2

class events(models.Model):
    titles = models.ForeignKey(Titles, on_delete=models.CASCADE)
    event = models.CharField(max_length = 100)
    date = models.DateTimeField(default = datetime.now)
    players = models.CharField(max_length = 100)
    

mysite/events/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Posts, odds, events
from home.models import Titles

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['team_1', 'team_2', 'bet_ammount', 'receive_ammount','result']

class oddsForm(forms.ModelForm):
    class Meta:
        model= odds
        fields = ['team_1', 'team_2', 'event', 'odds', 'result']
        
class eventsForm(forms.ModelForm):
    class Meta:
        model = events
        fields = ['titles','event', 'date', 'players']

mysite/events/views.py
from django.shortcuts import render,redirect, get_object_or_404
from home.models import Titles
from .models import Posts, odds
from django.views.generic import View
from django.db.models import Q
from .forms import PostForm, oddsForm, eventsForm


def create_post(request, titles_Title):
    titles = get_object_or_404(Titles, Title = titles_Title, user=request.user)
    form = PostForm(request.POST or None, request.FILES or None)
    form2 = oddsForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit = False)
        post.titles = get_object_or_404(Titles, Title = titles.Title, user=request.user)
        post.save()
        posts = Posts.objects.filter(titles_id = titles.id)
            
        return render(request, 'events/post_details.html', {'posts':posts, 'titles':titles})
    if form2.is_valid():
            odd = form2.save(commit = False)
            odd.titles = get_object_or_404(Titles, Title = titles.Title, user=request.user)
            odd.save()
            odd = odds.objects.filter(titles_id = titles.id)
            return render(request, 'events/post_details.html', {'odds':odd, 'titles':titles})
    return render(request, 'events/Posts.html', {'form':form, 'form2': form2, 'titles':titles})

def post_details(request, titles_Title):
    titles = get_object_or_404(Titles, Title = titles_Title, user=request.user)
    posts = Posts.objects.filter(titles = titles)
    return render(request, 'events/post_details.html',{'posts':posts, 'titles':titles})

def book_details(request, titles_Title):
    titles = get_object_or_404(Titles, Title = titles_Title, user=request.user)
    book = odds.objects.filter(titles = titles)
    return render(request, 'events/book_details.html', {'book':book, 'titles':titles})

def events_form(request):
    titles = Titles.objects.filter(user=request.user)
    form = eventsForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        title = form.save(commit=False)
        title.user = request.user
        title.save()
        return render(request, 'home/home.html', {'titles':titles})
    return render(request, 'events/events_template.html', {'form':form})



class AjaxTemplateMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(self, 'ajax_template_name'):
            split = self.template_name.split('.html')
            split[-1] = '_inner'
            split.append('.html')
            self.ajax_template_name = ''.join(split)
        if request.is_ajax():
            self.template_name = self.ajax_template_name
        return super(AjaxTemplateMixin, self).dispatch(request, *args, **kwargs)

mysite/events/templates/events/Posts.html
{% extends "home/header.html" %}
{% block content %}
<head>
    {% load staticfiles %}
    <title> My Webpage</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

</head>
<body >
    <div class="col-sm-8 col-md-9" >

        <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <li role="presentation" class = active><a href="{% url 'events:post_details' titles.Title %}">View bets </a></li>
            <li role="presentation" class="active"><a href="">Place bet</a></li>
            <li role = "presentation" class = active><a href = "{% url 'events:book_details' titles.Title %}">View Book</a></li>
        </ul>
    </div>
    <div class="row" >
        <div class="panel panel-default col-md-6" style = 'background-color:#f5f5dc;height:400px;'>
            <h3>Update Your Bets {{titles.Title}}</h3>
            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="album" value="{{ album }}">
                {% include 'events/form_template.html' %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>

            
        </div>
        <div class="panel panel-default col-md-6" style = 'background-color:#f5f5dc;height:400px;'>
            <h3> Update Your Book {{titles.Title}} </h3>
            <form class = "form-horizontal" role="form" aciton = "" method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type = "hidden" name = "form2">
                {% include 'events/form2_template.html' %}
                <div class = "form-group">
                    <div class = "col-sm-offset-2 col-sm-10">
                        <button type="submit" class = "btn btn-success"> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</body>

{% endblock %}

mysite/events/templates/events/book_details.html
{% extends "home/header.html" %}
{% block content %}
<body>
    <div class="container-fluid songs-container">

        <div class="row">


            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="{% url 'events:post_details' titles.Title %}">View bets</a></li>
                    <li role="presentation" class = "active"><a href="{% url 'events:create_post' titles.Title %}">Place bet</a></li>
                    <li role = "presentation" class = active><a href = "{% url 'events:book_details' titles.Title %}">View Book</a></li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>Bets</h3>


                        <table class="table table-striped">
                            <thead>

                            <tr>
                                <th> team 1 </th>
                                <th> team 2 </th>
                                <th> odds  </th>
                                <th>Results</th>

                            </tr>
                            </thead>
                            <tbody>
                                {% for bets in book %}
                                    <tr>
                                        <td> {{bets.team_1}}
                                        <td> {{bets.team_2}}
                                        <td> {{ bets.odds }} </td>
                                        <td > {{bets.result}}</td>
                                    </tr>

                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>

            </div>

        </div>

    </div>
    <style type='text/css'>

    table {
      border-collapse: separate;
      border-spacing: 0 5px;
    }

    thead th {
      background-color: #006DCC;
      color: white;
    }

    tbody td {
      background-color: #EEEEEE;
    }

    tr td:first-child,
    tr th:first-child {
      border-top-left-radius: 6px;
      border-bottom-left-radius: 6px;
    }

    tr td:last-child,
    tr th:last-child {
      border-top-right-radius: 6px;
      border-bottom-right-radius: 6px;
    }
</style>
</body>

{% endblock %}

mysite/events/templates/events/details.html
<!doctype html>

{% extends "home/header.html" %}
{% block Titles_active %}active{% endblock %}
{% block content %}
<head>
    {% load staticfiles %}
    <title> My Webpage</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

</head>
    <body>
        <div class="container" >
            <div class="panel panel-default" style="max-width:400px;margin-left:auto; margin-right:auto;">
                <div class = "panel-heading"> Live betting - Match winner <a href = "">Add event </a></div>
                <div class = "panel-body" >
                    <table class= "table table-striped table-bordered table-hover">
                        <thead>
                            <tr >

                            <th>Player 1</th>
                            <th>Player 2</th>  
                            </tr>
                        </thead>
                        <tbody data-link="row" class = "rowlink">
                            {% for event in titles.event_set.all %}
                                <tr onclick="window.document.location= '{% url 'events:create_post' titles.Title event.id %}';">
                                        <td>{{event.team_1}} </td>
                                        <td > {{event.team_2}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>   
        </div>




        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Launch demo modal
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
              </div>
              <div class="modal-body">
                ...
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>

        <script src="https://code.jquery.com/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.css"></script>
        <script src="https://code.jquery.com/jquery.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    </body>
<style type='text/css'>
    


    table {
      border-collapse: separate;
      border-spacing: 0 5px;
    }

    thead th {
      background-color: #006DCC;
      color: white;
    }

    tbody td {
      background-color: #EEEEEE;
    }

    tr td:first-child,
    tr th:first-child {
      border-top-left-radius: 6px;
      border-bottom-left-radius: 6px;
    }

    tr td:last-child,
    tr th:last-child {
      border-top-right-radius: 6px;
      border-bottom-right-radius: 6px;
    }
</style>
{% endblock %}

mysite/events/templates/events/events_template.html
<div class="modal hide" id="contactModal">
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="album" value="{{ album }}">
        {% for field in form %}
		    <div class="form-group">
		        <div class="col-sm-offset-2 col-sm-10">
		            <span class="text-danger small">{{ field.errors }}</span>
		        </div>
		        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
		        <div class="col-sm-10">{{ field }}</div>
		    </div>
		{% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>

mysite/events/templates/events/form2_template.html
{% for field in form2 %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/events/templates/events/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/events/templates/events/post_details.html
{% extends "home/header.html" %}
{% block content %}
<body>
    <div class="container-fluid songs-container">

        <div class="row">


            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="{% url 'events:post_details' titles.Title %}">View bets</a></li>
                    <li role="presentation"><a href="{% url 'events:create_post' titles.Title %}">Place bet</a></li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>Bets</h3>


                        <table class="table table-striped">
                            <thead>

                            <tr>
                                <th> team 1 </th>
                                <th> team 2 </th>
                                <th> Stake  </th>
                                <th>Results</th>

                            </tr>
                            </thead>
                            <tbody>
                                {% for bets in posts %}
                                    <tr>
                                        <td> {{bets.team_1}}
                                        <td> {{bets.team_2}}
                                        <td> {{ bets.bet_ammount }} : {{bets.receive_ammount}}</td>
                                        <td > {{bets.result}}</td>
                                    </tr>

                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>

            </div>

        </div>

    </div>
    <style type='text/css'>

    table {
      border-collapse: separate;
      border-spacing: 0 5px;
    }

    thead th {
      background-color: #006DCC;
      color: white;
    }

    tbody td {
      background-color: #EEEEEE;
    }

    tr td:first-child,
    tr th:first-child {
      border-top-left-radius: 6px;
      border-bottom-left-radius: 6px;
    }

    tr td:last-child,
    tr th:last-child {
      border-top-right-radius: 6px;
      border-bottom-right-radius: 6px;
    }
</style>
</body>

{% endblock %}